### ISSUE TITLE
ReferenceError: Can't find variable: onSuccess encountered when running on iOS

### ISSUE THREAD

**Issue by veelci** [KlaasVanDerLinden/cordova-plugin-notifications-permission#2]
"ReferenceError: Can't find variable: onSuccess" encountered when using this plugin on iOS.

It looks like `onResult` should be used instead of `onSuccess`.

**Comment by KlaasVanDerLinden** [comment]
Thanks for pointing this out! I actually never tested the plugin on iOS. My bad.
